schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PipelineComponentInput"
  types:
    PipelineComponentInput:
      type: object
      description: "Input properties for the pipeline component"
      properties:
        github_connection_arn:
          type: string
          description: "The ARN of the GitHub CodeStar connection"
          pattern: "^arn:aws:codestar-connections:[a-z0-9-]+:[0-9]{12}:connection/[a-f0-9-]+$"
      required:
        - repository_name
        - github_connection_arn