schema:
  format:
    openapi: "3.0.0"
  service_input_type: "SpringBootServiceInput"
  types:
    SpringBootServiceInput:
      type: object
      description: "Input properties for the Spring Boot service"
      properties:
        image_url:
          type: string
          description: "The URL of the Docker image to deploy"
          pattern: "^[a-zA-Z0-9][a-zA-Z0-9-_./]*$"
        container_port:
          type: number
          description: "The port number the application listens on"
          default: 8080
          minimum: 1
          maximum: 65535
        task_cpu:
          type: number
          description: "The number of CPU units for the task"
          default: 256
          enum: [256, 512, 1024, 2048, 4096]
        task_memory:
          type: number
          description: "The amount of memory (in MiB) for the task"
          default: 512
          enum: [512, 1024, 2048, 4096, 8192, 16384]
        desired_count:
          type: number
          description: "The desired number of tasks to run"
          default: 1
          minimum: 1
          maximum: 100
      required:
        - image_url